version: '3'
services:

  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - postgres

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"

  postgres:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
