name: check

on:
  workflow_dispatch:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install ruff==0.1.6
      - name: Lint Python
        run: ruff . --output-format github
